# Local settings

# Site settings
title: <%= projectTitle %>
description: <%= projectDescription %>
baseurl: ''
url: localhost:4000

author:
    name: <%= authorName %>
    email: <%= authorEmail %>
    bio: <%= authorBio %>
    github: <%= authorGithub %>

# Build settings
markdown: kramdown
