# Local Settings
#
title: <%= project_title %>
description: <%= project_description %>

baseurl: ''
url: localhost:4000
source: _source
destination: _deploy

author:
    name: <%= author_name %>
    email: <%= author_email %>
    bio: <%= author_bio %>
    github: <%= author_github %>

# Build settings
markdown: kramdown
